# Generated by Django 4.2.23 on 2025-07-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croplisting',
            old_name='price',
            new_name='rate',
        ),
    ]
