# Generated by Django 4.2.23 on 2025-07-17 20:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_price_croplisting_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croplisting',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP'),
        ),
    ]
