# Generated by Django 4.2.23 on 2025-07-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_croplisting_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropimage',
            name='image',
            field=models.ImageField(upload_to='marketplace/crop_images/'),
        ),
        migrations.AlterField(
            model_name='croplisting',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/crop_videos/'),
        ),
    ]
