# Generated by Django 4.2.23 on 2025-08-03 16:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_cropimage_image_alter_croplisting_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croplisting',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='marketplace/crop_videos/'),
        ),
    ]
