# Generated by Django 4.2.23 on 2025-07-15 08:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP'),
        ),
    ]
