# Generated by Django 4.2.23 on 2025-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_otprequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
