# Generated by Django 4.2.23 on 2025-07-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='image',
            field=models.ImageField(upload_to='mediafiles/detections/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='mediafiles/products/'),
        ),
    ]
