# Generated by Django 4.2.23 on 2025-07-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0003_suggestedagroservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestedAgroService',
        ),
    ]
