# Generated by Django 4.2.23 on 2025-07-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0004_delete_suggestedagroservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='image',
            field=models.ImageField(upload_to='detections/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
