# Generated by Django 4.2.23 on 2025-08-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0005_alter_detectionrecord_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
